version: '3.9'

services:
  recipevault-postgres:
    image: postgres:16
    container_name: recipevault-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipevault_db
    ports:
      - "5432:5432"
    volumes:
      - recipevault_pgdata:/var/lib/postgresql/data

  recipevault-redis:
    image: redis:alpine
    container_name: recipevault-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: recipevault-redis
      REDIS_PORT: 6379

volumes:
  recipevault_pgdata:
